import { StyleSheet } from "react-native";
import { radius, spacing, typography } from "../../../theme/theme";

export const revolutColors = {
  background: "#F5F6F8",
  surface: "#FFFFFF",
  secondarySurface: "#F1F3F5",
  text: "#111318",
  secondaryText: "#717680",
  mutedText: "#A1A5AC",
  border: "#E7E9ED",
  divider: "#E7E9ED",
  purple: "#6D56F5",
  brightPurple: "#765CFF",
  softPurple: "#F1EEFF",
  positive: "#22A96B",
  positiveSoft: "#E7F7EF",
  blue: "#3478F6",
  blueSoft: "#EAF2FF",
  warning: "#E9A237",
  warningSoft: "#FEF5E6",
  negative: "#E45F5F",
  negativeSoft: "#FCEEEE",
  coral: "#E8756D",
  coralSoft: "#FFF0EE",
  deepViolet: "#5547C9",
};

export const revolutStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: revolutColors.background },
  content: { paddingTop: spacing.md, paddingBottom: spacing.xl },
  header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: spacing.lg },
  headerCopy: { flex: 1, minWidth: 0 },
  brand: { fontFamily: "SourceSansPro-Bold", fontSize: 18, lineHeight: 22, color: revolutColors.text },
  headerMeta: { ...typography.small, color: revolutColors.secondaryText, marginTop: 2 },
  avatar: { width: 34, height: 34, borderRadius: 10, alignItems: "center", justifyContent: "center", backgroundColor: revolutColors.softPurple },
  avatarText: { fontFamily: "SourceSansPro-Bold", fontSize: 15, color: revolutColors.purple },
  accountSummary: { backgroundColor: "transparent", paddingVertical: spacing.xs, marginBottom: spacing.sm },
  summaryTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.md },
  eyebrow: { ...typography.label, color: revolutColors.secondaryText, textTransform: "uppercase", letterSpacing: 0.4 },
  summaryPercent: { ...typography.small, color: revolutColors.secondaryText },
  accountAmount: { fontFamily: "SourceSansPro-Bold", fontSize: 36, lineHeight: 40, color: revolutColors.text, marginTop: spacing.xs },
  accountMeta: { ...typography.small, color: revolutColors.secondaryText, marginTop: 1 },
  summaryRule: { height: 1, backgroundColor: revolutColors.divider, marginVertical: spacing.md },
  summaryFooter: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  summaryFooterLabel: { ...typography.small, color: revolutColors.secondaryText },
  summaryFooterValue: { fontFamily: "SourceSansPro-SemiBold", fontSize: 14, color: revolutColors.text },
  quickActions: { flexDirection: "row", gap: spacing.sm, marginBottom: spacing.md },
  quickAction: { flex: 1, minHeight: 40, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: spacing.xs, borderWidth: 1, borderColor: revolutColors.border, borderRadius: 10, backgroundColor: revolutColors.surface, paddingHorizontal: spacing.xs },
  quickActionPrimary: { backgroundColor: revolutColors.blue, borderColor: revolutColors.blue },
  quickActionSecondary: { backgroundColor: revolutColors.surface },
  quickActionTertiary: { backgroundColor: revolutColors.softPurple, borderColor: revolutColors.softPurple },
  quickActionText: { fontFamily: "SourceSansPro-SemiBold", fontSize: 12, color: revolutColors.text },
  quickActionTextOnPrimary: { color: revolutColors.surface },
  safeSpendCard: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.md, borderTopWidth: 1, borderBottomWidth: 1, borderColor: revolutColors.border, paddingVertical: spacing.md, marginBottom: spacing.md },
  safeSpendCopy: { flex: 1, minWidth: 0 },
  safeSpendIcon: { width: 28, height: 28, borderRadius: 8, backgroundColor: revolutColors.softPurple, alignItems: "center", justifyContent: "center", marginBottom: spacing.xs },
  moduleEyebrow: { ...typography.label, color: revolutColors.secondaryText },
  safeSpendAmount: { fontFamily: "SourceSansPro-Bold", fontSize: 29, lineHeight: 34, color: revolutColors.text, marginTop: 2 },
  safeSpendStatus: { ...typography.small, color: revolutColors.positive, fontFamily: "SourceSansPro-SemiBold", marginTop: 2 },
  safeSpendStatusWarning: { color: revolutColors.warning },
  safeSpendStatusDanger: { color: revolutColors.negative },
  safeSpendStatusNeutral: { color: revolutColors.secondaryText },
  safeSpendAside: { alignItems: "flex-end" },
  safeSpendAsideLabel: { ...typography.small, color: revolutColors.mutedText },
  safeSpendAsideValue: { fontFamily: "SourceSansPro-SemiBold", fontSize: 15, color: revolutColors.text, marginTop: 2 },
  module: { backgroundColor: revolutColors.surface, borderWidth: 1, borderColor: revolutColors.border, borderRadius: 12, padding: spacing.lg, marginBottom: spacing.md },
  moduleHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.md, marginBottom: spacing.md },
  moduleTitle: { fontFamily: "SourceSansPro-SemiBold", fontSize: 17, lineHeight: 21, color: revolutColors.text },
  moduleAction: { ...typography.small, color: revolutColors.purple, fontFamily: "SourceSansPro-SemiBold" },
  analyticsSummary: { flexDirection: "row", justifyContent: "space-between", gap: spacing.md, marginBottom: spacing.sm },
  analyticsValue: { fontFamily: "SourceSansPro-SemiBold", fontSize: 20, color: revolutColors.text, marginTop: 1 },
  analyticsValueMuted: { ...typography.small, color: revolutColors.secondaryText, marginTop: 1 },
  analyticsProgress: { height: 6, borderRadius: 3, marginTop: spacing.xs },
  analyticsFooter: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: spacing.xs },
  analyticsFooterText: { ...typography.small, color: revolutColors.secondaryText },
  analyticsChartHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: spacing.lg, marginBottom: spacing.sm },
  analyticsChartTitle: { ...typography.label, color: revolutColors.secondaryText },
  analyticsChartPeriod: { ...typography.small, color: revolutColors.secondaryText },
  analyticsChart: { height: 84, flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", gap: spacing.xs, paddingTop: spacing.sm, borderBottomWidth: 1, borderBottomColor: revolutColors.divider },
  chartColumn: { flex: 1, height: "100%", alignItems: "center", justifyContent: "flex-end", gap: 3 },
  chartTrack: { width: "70%", height: "82%", justifyContent: "flex-end", backgroundColor: revolutColors.secondarySurface, borderRadius: 3, overflow: "hidden" },
  chartBar: { width: "100%", backgroundColor: revolutColors.blue, borderRadius: 3, minHeight: 2 },
  chartDay: { ...typography.small, color: revolutColors.mutedText, fontSize: 10, lineHeight: 12 },
  categoryHeader: { ...typography.label, color: revolutColors.secondaryText, marginTop: spacing.lg, marginBottom: spacing.xs },
  categoryRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm, paddingVertical: spacing.sm, borderBottomWidth: 1, borderBottomColor: revolutColors.divider },
  categoryRowLast: { borderBottomWidth: 0 },
  categoryIcon: { width: 28, height: 28, borderRadius: 8, alignItems: "center", justifyContent: "center" },
  categoryCopy: { flex: 1, minWidth: 0 },
  categoryName: { fontFamily: "SourceSansPro-SemiBold", fontSize: 13, color: revolutColors.text },
  categoryBar: { height: 3, borderRadius: 2, backgroundColor: revolutColors.secondarySurface, marginTop: 4, overflow: "hidden" },
  categoryBarFill: { height: "100%", borderRadius: 2 },
  categoryAmount: { fontFamily: "SourceSansPro-SemiBold", fontSize: 13, color: revolutColors.text },
  compactSectionHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: spacing.sm },
  compactSectionTitle: { fontFamily: "SourceSansPro-SemiBold", fontSize: 17, color: revolutColors.text },
  goalsModule: { backgroundColor: revolutColors.surface, borderWidth: 1, borderColor: revolutColors.border, borderRadius: 12, padding: spacing.md, marginBottom: spacing.md },
  goalPreview: { flexDirection: "row", alignItems: "center", gap: spacing.md },
  goalPreviewIcon: { width: 40, height: 40, borderRadius: 10, alignItems: "center", justifyContent: "center" },
  goalPreviewCopy: { flex: 1, minWidth: 0 },
  goalPreviewName: { fontFamily: "SourceSansPro-SemiBold", fontSize: 15, color: revolutColors.text },
  goalPreviewMeta: { ...typography.small, color: revolutColors.secondaryText, marginTop: 1 },
  goalPreviewPercent: { fontFamily: "SourceSansPro-SemiBold", fontSize: 13, color: revolutColors.purple },
  goalPreviewProgress: { height: 5, borderRadius: 3, marginTop: spacing.md },
  goalPreviewFooter: { flexDirection: "row", justifyContent: "space-between", marginTop: spacing.xs },
  goalPreviewFooterText: { ...typography.small, color: revolutColors.secondaryText },
  transactionsModule: { backgroundColor: revolutColors.surface, borderWidth: 1, borderColor: revolutColors.border, borderRadius: 12, paddingHorizontal: spacing.lg, marginBottom: spacing.md },
  transactionRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm, paddingVertical: spacing.sm, borderBottomWidth: 1, borderBottomColor: revolutColors.divider },
  transactionRowLast: { borderBottomWidth: 0 },
  transactionIcon: { width: 30, height: 30, borderRadius: 8, alignItems: "center", justifyContent: "center" },
  transactionCopy: { flex: 1, minWidth: 0 },
  transactionTitle: { fontFamily: "SourceSansPro-SemiBold", fontSize: 14, color: revolutColors.text },
  transactionMeta: { ...typography.small, color: revolutColors.secondaryText, marginTop: 1 },
  transactionAmount: { fontFamily: "SourceSansPro-SemiBold", fontSize: 13, color: revolutColors.text },
  emptyCopy: { ...typography.small, color: revolutColors.secondaryText, marginBottom: spacing.sm },
  emptyButton: { alignSelf: "flex-start", minHeight: 38, borderRadius: 10, borderColor: revolutColors.purple, paddingHorizontal: spacing.md },
  emptyButtonText: { fontFamily: "SourceSansPro-SemiBold", fontSize: 13, color: revolutColors.purple },
  goalsSummaryWrap: { paddingVertical: spacing.xs, marginBottom: spacing.md },
  goalsSummary: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", gap: spacing.md },
  goalsSummaryAmount: { fontFamily: "SourceSansPro-Bold", fontSize: 32, lineHeight: 36, color: revolutColors.text, marginTop: 2 },
  goalsSummaryMeta: { ...typography.small, color: revolutColors.secondaryText, marginTop: 1 },
  goalsSummaryRight: { alignItems: "flex-end" },
  goalsSummaryRightValue: { fontFamily: "SourceSansPro-SemiBold", fontSize: 15, color: revolutColors.text },
  goalsSummaryRightLabel: { ...typography.small, color: revolutColors.secondaryText, marginTop: 1 },
  goalsSummaryProgress: { height: 5, borderRadius: 3 },
  segment: { flexDirection: "row", gap: spacing.xs, padding: 3, backgroundColor: revolutColors.secondarySurface, borderRadius: 10, marginBottom: spacing.md },
  segmentButton: { flex: 1, minHeight: 38, alignItems: "center", justifyContent: "center", borderRadius: 8 },
  segmentButtonActive: { backgroundColor: revolutColors.surface, borderWidth: 1, borderColor: revolutColors.border },
  segmentText: { fontFamily: "SourceSansPro-SemiBold", fontSize: 13, color: revolutColors.secondaryText },
  segmentTextActive: { color: revolutColors.text },
  goalGrid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.md },
  goalTile: { backgroundColor: revolutColors.surface, borderWidth: 1, borderColor: revolutColors.border, borderRadius: 12, overflow: "hidden" },
  goalVisual: { height: 86, position: "relative", overflow: "hidden", padding: spacing.md, justifyContent: "space-between" },
  goalVisualShape: { position: "absolute", width: 96, height: 96, borderRadius: 48, right: -28, top: -34 },
  goalVisualShapeSmall: { position: "absolute", width: 42, height: 42, borderRadius: 12, left: -12, bottom: -15, transform: [{ rotate: "18deg" }] },
  goalVisualTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.sm, zIndex: 1 },
  goalVisualIcon: { width: 32, height: 32, borderRadius: 9, alignItems: "center", justifyContent: "center" },
  goalVisualLabel: { fontFamily: "SourceSansPro-SemiBold", fontSize: 11, color: revolutColors.surface, letterSpacing: 0.5, zIndex: 1 },
  goalVisualMenu: { padding: 2 },
  goalTileBody: { padding: spacing.md },
  goalTileName: { fontFamily: "SourceSansPro-SemiBold", fontSize: 14, lineHeight: 18, color: revolutColors.text, minHeight: 36 },
  goalTileAmount: { fontFamily: "SourceSansPro-Bold", fontSize: 22, lineHeight: 26, color: revolutColors.text, marginTop: spacing.md },
  goalTileTarget: { ...typography.small, color: revolutColors.secondaryText, marginTop: 1 },
  goalTileProgress: { height: 5, borderRadius: 3, marginTop: spacing.md },
  goalTileFooter: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: spacing.xs },
  goalTilePercent: { fontFamily: "SourceSansPro-SemiBold", fontSize: 12 },
  goalTileLeft: { ...typography.small, color: revolutColors.secondaryText },
  goalsEmpty: { paddingVertical: spacing.md },
  goalsEmptyTitle: { fontFamily: "SourceSansPro-SemiBold", fontSize: 16, color: revolutColors.text },
  goalsEmptyDescription: { ...typography.small, color: revolutColors.secondaryText, marginTop: 2, marginBottom: spacing.md },
  bottomNav: { flexDirection: "row", alignItems: "center", justifyContent: "space-around", borderTopWidth: 1, borderTopColor: revolutColors.border, backgroundColor: revolutColors.surface, paddingTop: 6, paddingBottom: spacing.xs, marginTop: spacing.sm },
  bottomNavItem: { alignItems: "center", justifyContent: "center", gap: 2, minWidth: 48 },
  bottomNavLabel: { fontFamily: "SourceSansPro-SemiBold", fontSize: 10, color: revolutColors.mutedText },
  bottomNavLabelActive: { color: revolutColors.purple },
});
