import { StyleSheet } from "react-native";

export const copilotColors = {
  background: "#050D18",
  secondaryBackground: "#081526",
  surface: "#0A1A2D",
  surfaceRaised: "#0D2035",
  text: "#F5F7FA",
  textMuted: "#8EA2BA",
  textSubtle: "#647991",
  border: "#14304D",
  purple: "#775EF7",
  blue: "#3F91FF",
  green: "#18C97B",
  amber: "#F6B93B",
  red: "#FF5E62",
  white: "#FFFFFF",
};

export const copilotStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: copilotColors.background },
  content: { paddingHorizontal: 16, paddingBottom: 0, backgroundColor: copilotColors.background },
  header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingTop: 19, paddingBottom: 17 },
  headerCopy: { flex: 1, minWidth: 0 },
  brand: { fontFamily: "SourceSansPro-Bold", fontSize: 21, lineHeight: 26, color: copilotColors.text },
  headerMeta: { fontFamily: "SourceSansPro-Regular", fontSize: 12, lineHeight: 16, color: copilotColors.textMuted, marginTop: 2 },
  avatar: { width: 36, height: 36, borderRadius: 18, backgroundColor: copilotColors.purple, alignItems: "center", justifyContent: "center" },
  avatarText: { fontFamily: "SourceSansPro-Bold", fontSize: 16, color: copilotColors.white },
  headerIcons: { flexDirection: "row", alignItems: "center", gap: 15, marginLeft: 14 },
  headerIcon: { padding: 3 },
  hero: { backgroundColor: copilotColors.surface, borderWidth: 1, borderColor: copilotColors.border, borderRadius: 16, padding: 18, marginBottom: 13 },
  heroTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  eyebrow: { fontFamily: "SourceSansPro-SemiBold", fontSize: 11, lineHeight: 15, letterSpacing: 0.75, textTransform: "uppercase", color: copilotColors.textMuted },
  heroAmount: { fontFamily: "SourceSansPro-Bold", fontSize: 39, lineHeight: 44, letterSpacing: -0.6, color: copilotColors.text, marginTop: 5 },
  heroMeta: { fontFamily: "SourceSansPro-Regular", fontSize: 13, lineHeight: 18, color: copilotColors.textMuted, marginTop: 2 },
  heroStatus: { fontFamily: "SourceSansPro-SemiBold", fontSize: 13, lineHeight: 18, color: copilotColors.green, marginTop: 8 },
  heroStatusWarning: { color: copilotColors.amber },
  heroStatusDanger: { color: copilotColors.red },
  heroStatusNeutral: { color: copilotColors.textMuted },
  paceHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 20, marginBottom: 5 },
  paceTitle: { fontFamily: "SourceSansPro-SemiBold", fontSize: 13, lineHeight: 17, color: copilotColors.text },
  paceDelta: { fontFamily: "SourceSansPro-SemiBold", fontSize: 12, lineHeight: 16, color: copilotColors.green },
  paceDeltaWarning: { color: copilotColors.amber },
  paceDeltaDanger: { color: copilotColors.red },
  paceChart: { height: 108, flexDirection: "row", alignItems: "flex-end", gap: 5, borderBottomWidth: 1, borderBottomColor: copilotColors.border, paddingTop: 8 },
  paceColumn: { flex: 1, height: "100%", alignItems: "center", justifyContent: "flex-end" },
  pacePlot: { width: "100%", flex: 1, flexDirection: "row", alignItems: "flex-end", justifyContent: "center", gap: 2 },
  paceExpectedBar: { width: 4, borderRadius: 2, backgroundColor: copilotColors.border, minHeight: 2 },
  paceActualBar: { width: 5, borderRadius: 2, backgroundColor: copilotColors.blue, minHeight: 2 },
  paceActualBarPositive: { backgroundColor: copilotColors.green },
  paceActualBarDanger: { backgroundColor: copilotColors.red },
  paceLabel: { fontFamily: "SourceSansPro-Regular", fontSize: 9, lineHeight: 12, color: copilotColors.textSubtle, marginTop: 5 },
  legend: { flexDirection: "row", alignItems: "center", gap: 13, marginTop: 10 },
  legendItem: { flexDirection: "row", alignItems: "center", gap: 5 },
  legendSwatch: { width: 7, height: 7, borderRadius: 4 },
  legendText: { fontFamily: "SourceSansPro-Regular", fontSize: 10, lineHeight: 13, color: copilotColors.textSubtle },
  surface: { backgroundColor: copilotColors.surface, borderWidth: 1, borderColor: copilotColors.border, borderRadius: 14, padding: 16, marginBottom: 13 },
  sectionHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 14 },
  sectionTitle: { fontFamily: "SourceSansPro-SemiBold", fontSize: 16, lineHeight: 20, color: copilotColors.text },
  sectionLink: { fontFamily: "SourceSansPro-SemiBold", fontSize: 11, color: copilotColors.blue },
  moneyRow: { flexDirection: "row", justifyContent: "space-between", gap: 12 },
  stat: { flex: 1, minWidth: 0 },
  statRight: { alignItems: "flex-end" },
  statLabel: { fontFamily: "SourceSansPro-Regular", fontSize: 11, lineHeight: 15, color: copilotColors.textSubtle },
  statValue: { fontFamily: "SourceSansPro-Bold", fontSize: 22, lineHeight: 27, color: copilotColors.text, marginTop: 3 },
  statMeta: { fontFamily: "SourceSansPro-Regular", fontSize: 11, lineHeight: 15, color: copilotColors.textMuted, marginTop: 2 },
  progressTrack: { height: 5, borderRadius: 3, backgroundColor: copilotColors.border, overflow: "hidden", marginTop: 15 },
  progressFill: { height: "100%", borderRadius: 3, backgroundColor: copilotColors.blue },
  moduleFooter: { flexDirection: "row", justifyContent: "space-between", marginTop: 8 },
  footerText: { fontFamily: "SourceSansPro-SemiBold", fontSize: 11, lineHeight: 15, color: copilotColors.textMuted },
  footerAccent: { color: copilotColors.blue },
  categoryGrid: { flexDirection: "row", gap: 7 },
  categoryTile: { flex: 1, minWidth: 0, backgroundColor: copilotColors.surfaceRaised, borderWidth: 1, borderColor: copilotColors.border, borderRadius: 10, padding: 8 },
  categoryTileTop: { flexDirection: "row", alignItems: "center", gap: 5 },
  categoryDot: { width: 8, height: 8, borderRadius: 4 },
  categoryTileName: { flex: 1, minWidth: 0, fontFamily: "SourceSansPro-SemiBold", fontSize: 10, lineHeight: 13, color: copilotColors.textMuted },
  categoryTileAmount: { fontFamily: "SourceSansPro-Bold", fontSize: 14, lineHeight: 18, color: copilotColors.text, marginTop: 8 },
  categoryTileMeta: { fontFamily: "SourceSansPro-Regular", fontSize: 9, lineHeight: 12, color: copilotColors.textSubtle, marginTop: 1 },
  categoryBar: { height: 3, borderRadius: 2, backgroundColor: copilotColors.border, overflow: "hidden", marginTop: 7 },
  categoryBarFill: { height: "100%", borderRadius: 2 },
  recentRow: { flexDirection: "row", alignItems: "center", gap: 10, minHeight: 54, paddingVertical: 9, borderBottomWidth: 1, borderBottomColor: copilotColors.border },
  recentRowLast: { borderBottomWidth: 0 },
  recentIcon: { width: 30, height: 30, borderRadius: 8, alignItems: "center", justifyContent: "center" },
  recentCopy: { flex: 1, minWidth: 0 },
  recentTitle: { fontFamily: "SourceSansPro-SemiBold", fontSize: 13, lineHeight: 17, color: copilotColors.text },
  recentMeta: { fontFamily: "SourceSansPro-Regular", fontSize: 10, lineHeight: 14, color: copilotColors.textSubtle, marginTop: 1 },
  recentAmount: { fontFamily: "SourceSansPro-SemiBold", fontSize: 13, lineHeight: 17, color: copilotColors.text, textAlign: "right" },
  goalRow: { borderLeftWidth: 3, borderLeftColor: copilotColors.purple, paddingLeft: 12 },
  goalTop: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 12 },
  goalCopy: { flex: 1, minWidth: 0 },
  goalName: { fontFamily: "SourceSansPro-SemiBold", fontSize: 15, lineHeight: 19, color: copilotColors.text },
  goalAmount: { fontFamily: "SourceSansPro-Bold", fontSize: 21, lineHeight: 26, color: copilotColors.text, marginTop: 4 },
  goalTarget: { fontFamily: "SourceSansPro-Regular", fontSize: 11, lineHeight: 15, color: copilotColors.textMuted, marginTop: 1 },
  goalPercent: { fontFamily: "SourceSansPro-Bold", fontSize: 18, lineHeight: 23, color: copilotColors.purple },
  goalPercentLabel: { fontFamily: "SourceSansPro-Regular", fontSize: 10, color: copilotColors.textSubtle, textAlign: "right" },
  goalProgress: { height: 5, borderRadius: 3, backgroundColor: copilotColors.border, overflow: "hidden", marginTop: 15 },
  goalProgressFill: { height: "100%", borderRadius: 3 },
  goalFooter: { flexDirection: "row", justifyContent: "space-between", marginTop: 8 },
  goalFooterText: { fontFamily: "SourceSansPro-SemiBold", fontSize: 11, lineHeight: 15, color: copilotColors.textMuted },
  emptyCopy: { fontFamily: "SourceSansPro-Regular", fontSize: 13, lineHeight: 19, color: copilotColors.textMuted },
  bottomNav: { flexDirection: "row", paddingTop: 12, paddingBottom: 15, borderTopWidth: 1, borderTopColor: copilotColors.border, backgroundColor: copilotColors.background },
  bottomNavItem: { flex: 1, alignItems: "center", gap: 4 },
  bottomNavLabel: { fontFamily: "SourceSansPro-SemiBold", fontSize: 10, lineHeight: 13, color: copilotColors.textSubtle },
  bottomNavLabelActive: { color: copilotColors.blue },
  goalsHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingTop: 19, paddingBottom: 16 },
  goalsHeaderLeft: { flexDirection: "row", alignItems: "center", gap: 12, flex: 1, minWidth: 0 },
  backButton: { width: 30, height: 34, alignItems: "flex-start", justifyContent: "center" },
  goalsTitle: { fontFamily: "SourceSansPro-Bold", fontSize: 28, lineHeight: 33, color: copilotColors.text },
  goalsHeaderMeta: { fontFamily: "SourceSansPro-Regular", fontSize: 12, lineHeight: 16, color: copilotColors.textMuted, marginTop: 1 },
  addButton: { width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center", backgroundColor: copilotColors.purple },
  summarySurface: { backgroundColor: copilotColors.surface, borderWidth: 1, borderColor: copilotColors.border, borderRadius: 14, padding: 16, marginBottom: 12 },
  summaryTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end" },
  summaryAmount: { fontFamily: "SourceSansPro-Bold", fontSize: 34, lineHeight: 39, color: copilotColors.text, marginTop: 5 },
  summaryMeta: { fontFamily: "SourceSansPro-Regular", fontSize: 12, lineHeight: 16, color: copilotColors.textMuted, marginTop: 2 },
  summaryPercent: { fontFamily: "SourceSansPro-Bold", fontSize: 20, lineHeight: 25, color: copilotColors.purple },
  summaryPercentLabel: { fontFamily: "SourceSansPro-Regular", fontSize: 10, color: copilotColors.textSubtle, textAlign: "right" },
  tabRow: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: copilotColors.border, marginBottom: 5 },
  tabButton: { paddingVertical: 12, marginRight: 23, borderBottomWidth: 2, borderBottomColor: "transparent" },
  tabButtonActive: { borderBottomColor: copilotColors.purple },
  tabText: { fontFamily: "SourceSansPro-SemiBold", fontSize: 13, color: copilotColors.textMuted },
  tabTextActive: { color: copilotColors.text },
  goalSection: { marginBottom: 9 },
  listHeadingRow: { flexDirection: "row", alignItems: "baseline", justifyContent: "space-between", paddingTop: 16, paddingBottom: 3 },
  listHeading: { fontFamily: "SourceSansPro-SemiBold", fontSize: 16, lineHeight: 20, color: copilotColors.text },
  listCount: { fontFamily: "SourceSansPro-Regular", fontSize: 11, color: copilotColors.textSubtle },
  goalCard: { backgroundColor: copilotColors.surface, borderWidth: 1, borderColor: copilotColors.border, borderRadius: 12, padding: 14, marginTop: 9 },
  goalCardAccentPurple: { borderLeftColor: copilotColors.purple },
  goalCardAccentBlue: { borderLeftColor: copilotColors.blue },
  goalCardAccentTeal: { borderLeftColor: "#32B7AD" },
  goalCardAccentGreen: { borderLeftColor: copilotColors.green },
  emptyGoals: { paddingVertical: 46 },
  emptyGoalsTitle: { fontFamily: "SourceSansPro-Bold", fontSize: 20, lineHeight: 25, color: copilotColors.text },
  emptyGoalsDescription: { fontFamily: "SourceSansPro-Regular", fontSize: 13, lineHeight: 19, color: copilotColors.textMuted, marginTop: 6 },
  emptyGoalsButton: { alignSelf: "flex-start", minHeight: 42, paddingHorizontal: 18, borderRadius: 21, justifyContent: "center", alignItems: "center", backgroundColor: copilotColors.purple, marginTop: 17 },
  emptyGoalsButtonText: { fontFamily: "SourceSansPro-SemiBold", fontSize: 13, color: copilotColors.white },
  guidance: { backgroundColor: copilotColors.secondaryBackground, borderWidth: 1, borderColor: copilotColors.border, borderRadius: 12, padding: 13, marginTop: 16 },
  guidanceLabel: { fontFamily: "SourceSansPro-SemiBold", fontSize: 11, lineHeight: 15, color: copilotColors.blue, textTransform: "uppercase", letterSpacing: 0.6 },
  guidanceText: { fontFamily: "SourceSansPro-Regular", fontSize: 12, lineHeight: 17, color: copilotColors.textMuted, marginTop: 4 },
});
