import { StyleSheet } from "react-native";
import { colors, control, radius, spacing, typography } from "../../theme/theme";

export const styles = StyleSheet.create({
  welcomeContent: { flexGrow: 1, paddingTop: 52, paddingBottom: spacing.xl },
  welcomeBrandRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm, marginBottom: spacing.xxxl },
  brandMark: { width: 36, height: 36, borderRadius: radius.icon, backgroundColor: colors.primarySoft, alignItems: "center", justifyContent: "center" },
  brandName: { fontFamily: "Inter-SemiBold", fontSize: 18, color: colors.text },
  welcomeVisual: { height: 140, borderRadius: radius.hero, backgroundColor: colors.primarySoft, borderWidth: 1, borderColor: colors.border, padding: spacing.xl, marginBottom: spacing.xxxl, overflow: "hidden" },
  visualCircle: { position: "absolute", width: 96, height: 96, borderRadius: 48, borderWidth: 8, borderColor: colors.primary, right: 28, top: 23, opacity: 0.65 },
  visualCircleInner: { position: "absolute", width: 52, height: 52, borderRadius: 26, backgroundColor: colors.white, right: 50, top: 45 },
  visualLabel: { ...typography.label, color: colors.primary, marginTop: spacing.sm },
  visualAmount: { fontFamily: "Inter-Bold", fontSize: 24, color: colors.text, marginTop: spacing.xs },
  visualSubtext: { ...typography.small, color: colors.textMuted, marginTop: spacing.xs },
  welcomeHero: { marginBottom: spacing.xxxl },
  eyebrow: { ...typography.label, color: colors.primary, marginBottom: spacing.md },
  welcomeTitle: { ...typography.heading, color: colors.text, marginBottom: spacing.lg },
  welcomeSubtitle: { ...typography.body, maxWidth: 260 },
  featureList: { gap: 0, marginBottom: spacing.huge },
  featureRow: { flexDirection: "row", alignItems: "center", gap: spacing.md, paddingVertical: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.divider },
  featureRowLast: { borderBottomWidth: 0 },
  featureIcon: { width: control.iconSize, height: control.iconSize, borderRadius: radius.icon, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, alignItems: "center", justifyContent: "center" },
  featureCopy: { flex: 1 },
  featureTitle: { ...typography.section, color: colors.text, marginBottom: 2 },
  featureDescription: { ...typography.small },
  fullWidthButton: { width: "100%" },
  signInPrompt: { textAlign: "center", marginTop: spacing.lg, ...typography.small },
  link: { color: colors.primary, fontFamily: "Inter-SemiBold" },

  formContent: { paddingTop: spacing.lg, paddingBottom: spacing.huge },
  welcomeIntro: { marginTop: 42 },
  welcomeMark: { width: 56, height: 56, borderRadius: 28, backgroundColor: colors.text, alignItems: "center", justifyContent: "center", marginBottom: 40 },
  welcomeMarkText: { color: colors.background, fontFamily: "SourceSerifPro-Regular", fontSize: 31, lineHeight: 36, marginTop: -2 },
  welcomeActions: { marginTop: "auto", paddingTop: spacing.xxl },

  pocketMoneyContent: { flexGrow: 1, paddingTop: spacing.lg, paddingBottom: spacing.xl },
  onboardingBack: { marginBottom: 30 },
  onboardingIntro: { marginBottom: 32 },
  onboardingStep: { color: colors.accent, ...typography.eyebrow, marginBottom: 12 },
  pocketMoneyForm: { flex: 1 },
  pocketMoneyLabel: { ...typography.label, color: colors.text, marginTop: 28, marginBottom: spacing.sm },
  pocketMoneySplit: { marginTop: spacing.xxl, borderTopWidth: 1, borderTopColor: colors.divider, paddingTop: spacing.md },
  splitHeadingRow: { flexDirection: "row", alignItems: "baseline", justifyContent: "space-between" },
  splitTitle: { ...typography.label, color: colors.text },
  splitRatio: { ...typography.small, color: colors.textMuted },
  pocketSavingAmount: { color: colors.accent },
  pocketSpendingAmount: { color: colors.text },
  pocketSpendPercent: { color: colors.textMuted },
  onboardingBottomAction: { width: "100%", marginTop: spacing.xxl },
  goalFormContent: { flexGrow: 1, paddingTop: spacing.lg, paddingBottom: spacing.xl },
  goalFormCopy: { ...typography.body, marginTop: spacing.sm, maxWidth: 300 },
  goalForm: { flex: 1 },
  goalAmountField: { marginTop: 26 },
  goalEstimate: { ...typography.small, color: colors.accent, lineHeight: 19, marginTop: spacing.md },
  goalPrioritySection: { marginTop: 28 },
  goalPriorityTitle: { ...typography.section, color: colors.text, marginBottom: 12 },
  goalPriorityRow: { flexDirection: "row", gap: 10 },
  goalPriorityChoice: { flex: 1, minHeight: 48, borderWidth: 1, borderColor: colors.border, borderRadius: 8, alignItems: "center", justifyContent: "center" },
  goalPriorityActive: { backgroundColor: colors.primarySoft, borderColor: colors.accent },
  goalPriorityText: { fontFamily: "Inter-Regular", fontSize: 14, lineHeight: 20, color: colors.textMuted },
  goalPriorityTextActive: { color: colors.accent, fontFamily: "Inter-SemiBold" },
  expenseFormContent: { flexGrow: 1, paddingTop: spacing.lg, paddingBottom: spacing.xl },
  expenseIntro: { marginBottom: 32 },
  expenseForm: { flex: 1 },
  expenseMerchantField: { marginTop: 26 },
  expenseCategoryLabel: { ...typography.label, color: colors.textMuted, marginBottom: spacing.sm },
  expenseCategoryField: { marginTop: 26 },
  expenseCategorySelect: { minHeight: 52, borderWidth: 1, borderColor: "#D8D1C6", borderRadius: 8, backgroundColor: colors.inputSurface, paddingHorizontal: 16, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  expenseCategorySelectCopy: { flexDirection: "row", alignItems: "center", gap: spacing.md },
  balanceHint: { ...typography.small, color: colors.textMuted, textAlign: "center", marginTop: 12 },
  categoryFlowContent: { flexGrow: 1, paddingTop: spacing.lg, paddingBottom: spacing.xl },
  categoryList: { borderTopWidth: 1, borderTopColor: colors.divider },
  categoryListRow: { minHeight: 62, paddingHorizontal: spacing.xs, borderBottomWidth: 1, borderBottomColor: colors.divider, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  categoryListRowActive: { borderBottomColor: colors.divider },
  categoryListCopy: { flexDirection: "row", alignItems: "center", gap: spacing.md },
  categoryListActiveText: { color: colors.accent, fontFamily: "Inter-SemiBold" },
  reflectionContent: { flexGrow: 1, paddingTop: spacing.lg, paddingBottom: spacing.xl },
  flowContent: { flexGrow: 1, paddingHorizontal: spacing.xl, paddingTop: spacing.xl, paddingBottom: spacing.xl },
  flowCenterContent: { alignItems: "stretch" },
  flowHeader: { marginBottom: 22 },
  flowAvatar: { position: "absolute", right: 0, top: 0, width: 44, height: 44, borderRadius: radius.circle, backgroundColor: colors.surfaceMuted, borderWidth: 1, borderColor: colors.border, alignItems: "center", justifyContent: "center", zIndex: 1 },
  flowBack: { flexDirection: "row", alignItems: "center", gap: spacing.sm, height: 36, marginBottom: 22 },
  flowBackText: { fontFamily: "Inter-Regular", fontSize: 12, lineHeight: 18, color: colors.accent },
  flowEyebrow: { ...typography.eyebrow, color: colors.textMuted, marginBottom: 12 },
  flowTitle: { ...typography.heading, color: colors.text },
  flowField: { marginTop: 26, marginBottom: 26 },
  flowFieldLabel: { ...typography.label, color: colors.textMuted, marginBottom: spacing.sm },
  flowSelect: { minHeight: 52, borderWidth: 1, borderColor: colors.border, borderRadius: 10, paddingHorizontal: 16, flexDirection: "row", alignItems: "center", justifyContent: "space-between", backgroundColor: colors.surface },
  flowSelectCopy: { flexDirection: "row", alignItems: "center", gap: 10 },
  flowAvailable: { fontFamily: "Inter-Regular", fontSize: 11, lineHeight: 17, color: colors.textMuted, textAlign: "center", marginTop: 12 },
  flowActions: { marginTop: "auto", paddingTop: 32 },
  changePasswordContent: { flexGrow: 1, paddingHorizontal: spacing.xl, paddingTop: spacing.xl, paddingBottom: spacing.xl },
  changePasswordHeader: { marginBottom: spacing.sm },
  changePasswordEyebrow: { ...typography.eyebrow, color: colors.textMuted, marginBottom: 12 },
  changePasswordTitle: { paddingRight: 56, minHeight: 44 },
  changePasswordCopy: { ...typography.body, color: colors.textMuted, marginBottom: spacing.xxl, maxWidth: 300 },
  changePasswordField: { marginBottom: spacing.lg },
  changePasswordFormError: { ...typography.small, color: colors.danger, marginTop: -spacing.sm, marginBottom: spacing.sm },
  changePasswordActions: { marginTop: "auto", paddingTop: 32 },
  addMoneyActions: { gap: spacing.md },
  goalDetailsBackButton: { width: "100%" },
  goalDetailsActions: { gap: spacing.md },
  goalDetailsDeleteButton: { width: "100%" },
  flowEmpty: { alignItems: "flex-start", marginTop: 55 },
  flowEmptyIcon: { width: 42, height: 42, borderRadius: 21, backgroundColor: colors.primarySoft, alignItems: "center", justifyContent: "center", marginBottom: 24 },
  flowEmptyTitle: { ...typography.section, color: colors.text, marginBottom: 8 },
  flowEmptyCopy: { ...typography.small, color: colors.textMuted, maxWidth: 260 },
  flowEmptyButton: { width: "100%", marginTop: 24 },
  goalDetailsCard: { backgroundColor: colors.primary, borderRadius: radius.card, padding: spacing.xl, marginBottom: spacing.xxl },
  goalDetailsLabel: { ...typography.small, color: "#D5CBBC" },
  goalDetailsAmountRow: { flexDirection: "row", alignItems: "baseline", gap: spacing.sm, marginTop: spacing.sm },
  goalDetailsAmount: { fontFamily: "Inter-Regular", fontSize: 34, lineHeight: 40, letterSpacing: -1, color: colors.background },
  goalDetailsTarget: { ...typography.small, color: "#D5CBBC" },
  goalDetailsProgress: { height: 4, borderRadius: 2, marginTop: spacing.xl },
  goalDetailsFooter: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: spacing.sm },
  goalDetailsFooterText: { ...typography.small, fontSize: 11, lineHeight: 16, color: "#D5CBBC" },
  goalDetailsSectionTitle: { ...typography.section, color: colors.text, marginBottom: spacing.sm },
  goalDetailsContainer: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.card, overflow: "hidden", marginBottom: spacing.xxl },
  goalDetailsRow: { minHeight: 52, paddingHorizontal: spacing.lg, paddingVertical: spacing.md, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  goalDetailsRowDivider: { borderBottomWidth: 1, borderBottomColor: colors.divider },
  goalDetailsValue: { ...typography.button, color: colors.text },
  flowSummary: { borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.divider },
  flowSummaryRow: { minHeight: 52, paddingVertical: 15, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: colors.divider },
  flowSummaryValue: { ...typography.button, color: colors.text },
  successMark: { width: 56, height: 56, borderRadius: 28, backgroundColor: colors.successSoft, alignItems: "center", justifyContent: "center", marginTop: 10, marginBottom: 28 },
  successAmount: { fontFamily: "Inter-SemiBold", fontSize: 18, lineHeight: 24, color: colors.text },
  successCopy: { ...typography.body, color: colors.textMuted, marginTop: 10, maxWidth: 280 },
  achievedRing: { width: 56, height: 56, borderRadius: 28, backgroundColor: colors.successSoft, alignItems: "center", justifyContent: "center", marginTop: 10, marginBottom: 28 },
  achievedName: { fontFamily: "Inter-SemiBold", fontSize: 16, lineHeight: 22, color: colors.text },
  achievedCopy: { ...typography.body, color: colors.textMuted, marginTop: 10 },
  reflectionIntro: { marginBottom: spacing.xxl },
  reflectionCopy: { ...typography.body, marginTop: spacing.sm, maxWidth: 300 },
  reflectionAmountRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.divider, paddingVertical: spacing.lg, marginBottom: spacing.md },
  reflectionBalance: { ...typography.small, color: colors.textMuted, textAlign: "right" },
  reflectionGoalHint: { ...typography.small, color: colors.accent, marginBottom: spacing.xxl },
  reflectionQuestion: { ...typography.section, color: colors.text, marginTop: 26, marginBottom: 10 },
  reflectionChoiceRow: { flexDirection: "row", gap: 10 },
  reflectionChoice: { flex: 1, minHeight: 48, borderWidth: 1, borderColor: "#D8D1C6", borderRadius: 8, alignItems: "center", justifyContent: "center", backgroundColor: "transparent" },
  reflectionChoiceSelected: { backgroundColor: "#EAE5DC", borderColor: "#978975" },
  reflectionChoiceText: { fontFamily: "Inter-Regular", fontSize: 14, lineHeight: 20, color: colors.textMuted },
  reflectionChoiceTextSelected: { color: colors.text },
  reflectionOptional: { ...typography.small, color: colors.textMuted },
  reflectionField: { marginTop: spacing.sm, marginBottom: spacing.lg },
  reflectionSaveButton: { marginTop: 12 },
  insightsContent: { paddingHorizontal: spacing.xl, paddingTop: spacing.sm, paddingBottom: spacing.lg },
  weeklyCard: { backgroundColor: colors.surfaceMuted, borderRadius: 12, paddingHorizontal: spacing.lg, paddingTop: spacing.lg, marginBottom: 10 },
  weeklyEyebrow: { ...typography.small, color: colors.textMuted },
  weeklyAmount: { fontFamily: "Inter-Regular", fontSize: 30, lineHeight: 36, letterSpacing: -1, color: colors.text, marginTop: spacing.xs },
  weeklyChart: { height: 128, flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", gap: spacing.sm, paddingTop: spacing.sm },
  weeklyDay: { width: 28, height: "100%", alignItems: "center", justifyContent: "flex-end" },
  weeklyBarArea: { height: 110, width: "100%", justifyContent: "flex-end", alignItems: "center" },
  weeklyBar: { width: "100%", borderTopLeftRadius: 5, borderTopRightRadius: 5 },
  weeklyLabel: { ...typography.small, fontSize: 11, color: colors.textMuted, marginTop: spacing.sm, marginBottom: spacing.md },
  insightsList: { gap: spacing.md },
  insightsCategoryRow: { flexDirection: "row", alignItems: "center", gap: spacing.md },
  insightsCategoryLast: { marginBottom: 0 },
  insightsCategoryHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  insightsActivityList: { marginTop: -spacing.sm },
  insightsSectionHeader: { marginTop: 16 },
  profileContent: { paddingHorizontal: spacing.xl, paddingTop: spacing.sm, paddingBottom: spacing.massive },
  profileIdentity: { flexDirection: "row", alignItems: "center", gap: spacing.md, marginBottom: spacing.xxxl, marginTop: spacing.sm },
  profileList: { borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.divider },
  detailRowLast: { borderBottomWidth: 0 },
  profileActionRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: spacing.md, borderBottomWidth: 1, borderColor: colors.divider },
  profileActionArrow: { color: colors.textMuted, fontFamily: "Inter-Regular", fontSize: 24, lineHeight: 24 },
  profileLogout: { paddingVertical: spacing.lg, marginTop: spacing.xl },
  profileLogoutText: { color: "#A34E43", fontFamily: "Inter-SemiBold", fontSize: 15 },
  stepRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm, marginBottom: spacing.xl },
  stepDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.border },
  stepDotActive: { width: 24, backgroundColor: colors.primary },
  screenTitle: { ...typography.heading, color: colors.text, marginBottom: spacing.sm },
  screenSubtitle: { ...typography.body, marginBottom: spacing.xxxl, maxWidth: 340 },
  fieldSpacing: { marginBottom: spacing.xxl },
  amountField: { height: control.inputHeight, fontFamily: "Inter-SemiBold", fontSize: 28, paddingHorizontal: spacing.xl },
  amountPrefix: { position: "absolute", zIndex: 1, left: spacing.lg, top: 40, fontFamily: "Inter-SemiBold", fontSize: 22, color: colors.textMuted },
  amountFieldWithPrefix: { paddingLeft: 42 },
  sectionLabel: { ...typography.label, color: colors.textMuted, marginBottom: spacing.sm },
  ratioHeading: { marginTop: spacing.xxxl },
  splitSummary: { flexDirection: "row", alignItems: "center", marginTop: spacing.sm },
  splitRight: { alignItems: "flex-end", flex: 1 },
  splitDivider: { width: 1, height: 52, backgroundColor: colors.divider, marginHorizontal: spacing.xl },
  smallLabel: { ...typography.small, color: colors.textMuted },
  splitAmount: { fontFamily: "Inter-SemiBold", color: colors.text, fontSize: 22, marginTop: 3 },
  spendingAmount: { color: colors.coral },
  savingAmount: { color: colors.success },
  percentText: { ...typography.small, color: colors.primary, marginTop: 2, fontFamily: "Inter-SemiBold" },
  spendingPercent: { color: colors.coral },
  savingPercent: { color: colors.success },
  sliderTouchArea: { height: 44, justifyContent: "center", marginTop: spacing.xl },
  sliderTrack: { height: control.progressHeight, borderRadius: control.progressHeight / 2, backgroundColor: colors.border, overflow: "hidden" },
  sliderFill: { height: "100%", backgroundColor: colors.primary, borderRadius: control.progressHeight / 2 },
  sliderThumb: { position: "absolute", width: 24, height: 24, borderRadius: 12, backgroundColor: colors.white, borderWidth: 6, borderColor: colors.primary, marginLeft: -12 },
  sliderLabels: { flexDirection: "row", justifyContent: "space-between", marginTop: spacing.xs },
  helperCard: { backgroundColor: colors.successSoft, borderRadius: radius.input, padding: spacing.lg, marginTop: spacing.xxl },
  helperText: { ...typography.small, lineHeight: 20, color: colors.textMuted },
  helperHighlight: { color: colors.success, fontFamily: "Inter-SemiBold" },

  goalChoiceIntro: { ...typography.body, color: colors.textMuted, marginBottom: spacing.lg },
  goalChoiceGrid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm },
  goalChoice: { width: "30.8%", minHeight: 96, borderWidth: 1, borderColor: colors.border, borderRadius: radius.input, backgroundColor: colors.surface, alignItems: "center", justifyContent: "center", padding: spacing.sm },
  goalChoiceActive: { backgroundColor: colors.primarySoft, borderColor: colors.primary },
  goalChoiceIcon: { width: 38, height: 38, borderRadius: 12, backgroundColor: colors.surfaceMuted, alignItems: "center", justifyContent: "center", marginBottom: spacing.sm },
  goalChoiceIconActive: { backgroundColor: colors.white },
  goalChoiceLabel: { ...typography.small, color: colors.textMuted, textAlign: "center" },
  goalChoiceLabelActive: { color: colors.primary, fontFamily: "Inter-SemiBold" },
  customChoice: { width: "100%", minHeight: 56, flexDirection: "row", justifyContent: "flex-start", gap: spacing.sm, paddingHorizontal: spacing.lg },
  customChoiceIcon: { marginBottom: 0 },
  detailsHeader: { flexDirection: "row", alignItems: "center", gap: spacing.md, marginBottom: spacing.xxl },
  detailsIcon: { width: 44, height: 44, borderRadius: radius.icon, backgroundColor: colors.primarySoft, alignItems: "center", justifyContent: "center" },
  detailsName: { fontFamily: "Inter-SemiBold", fontSize: 18, color: colors.text },
  detailsMeta: { ...typography.small, color: colors.textMuted, marginTop: 2 },
  estimateCard: { flexDirection: "row", alignItems: "center", gap: spacing.md, marginBottom: spacing.xxl, backgroundColor: colors.successSoft, borderColor: colors.successSoft },
  estimateIcon: { width: 38, height: 38, borderRadius: 12, backgroundColor: colors.white, alignItems: "center", justifyContent: "center" },
  estimateText: { fontFamily: "Inter-SemiBold", fontSize: 14, color: colors.text, lineHeight: 19, marginTop: 2 },
  previewHeading: { marginTop: spacing.xxxl },
  goalPreview: { flexDirection: "row", alignItems: "center", gap: spacing.md, marginTop: spacing.sm },
  previewIcon: { width: 44, height: 44, borderRadius: radius.icon, backgroundColor: colors.primarySoft, alignItems: "center", justifyContent: "center" },
  previewName: { fontFamily: "Inter-SemiBold", fontSize: 16, color: colors.text, marginTop: 2 },
  previewAmount: { fontFamily: "Inter-SemiBold", fontSize: 17, color: colors.text },

  completeContent: { flexGrow: 1, paddingTop: 52, paddingBottom: spacing.xl },
  completeIntro: { marginBottom: spacing.xxxl },
  successMark: { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.primarySoft, alignItems: "center", justifyContent: "center", marginBottom: spacing.xxl },
  successMarkText: { color: colors.accent, fontFamily: "Inter-Bold", fontSize: 25 },
  completeTitle: { ...typography.heading, color: colors.text, marginTop: spacing.sm },
  completeSubtitle: { ...typography.body, marginTop: spacing.sm, maxWidth: 280 },
  planSummary: { borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.divider },
  planTotal: { paddingVertical: spacing.xl, borderBottomWidth: 1, borderBottomColor: colors.divider },
  planTotalAmount: { fontFamily: "Inter-Regular", fontSize: 33, lineHeight: 37, letterSpacing: -1, color: colors.text, marginTop: 6 },
  planSplit: { flexDirection: "row", paddingVertical: spacing.xl },
  planSplitColumn: { flex: 1, minWidth: 0 },
  planSplitColumnRight: { alignItems: "flex-end" },
  planSplitDivider: { width: 1, backgroundColor: colors.divider, marginHorizontal: spacing.lg },
  planSplitAmount: { fontFamily: "Inter-SemiBold", fontSize: 20, lineHeight: 24, color: colors.text, marginTop: 5 },
  planSplitMeta: { ...typography.small, marginTop: 4 },
  firstGoalLine: { paddingVertical: spacing.xl, borderBottomWidth: 1, borderBottomColor: colors.divider },
  firstGoalText: { fontFamily: "Inter-SemiBold", fontSize: 16, color: colors.text },
  completeActions: { marginTop: "auto", paddingTop: spacing.xxxl },

  referenceScreen: { backgroundColor: colors.referenceBackground },
  dashboardShell: { flex: 1, backgroundColor: colors.referenceBackground },
  addMoneyKeyboard: { flex: 1, backgroundColor: colors.background },
  addMoneyBudget: { backgroundColor: colors.primarySoft, borderRadius: 12, padding: 18, marginTop: 26 },
  addMoneyBudgetLabel: { ...typography.small, color: colors.textMuted },
  addMoneyBudgetAmount: { fontFamily: "Inter-Regular", fontSize: 31, lineHeight: 36, letterSpacing: -0.7, color: colors.text, marginTop: 12 },
  addMoneyBudgetDecimals: { fontFamily: "Inter-Regular", fontSize: 12, lineHeight: 18, color: colors.textMuted, letterSpacing: 0, marginLeft: 7 },
  dashboardEmptyActivity: { paddingVertical: 28 },
  dashboardEmptyTitle: { ...typography.section, color: colors.text, marginBottom: 8 },
  dashboardEmptyCopy: { ...typography.small, color: colors.textMuted },
  dashboardFixedHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", backgroundColor: colors.referenceBackground, paddingHorizontal: spacing.xl, paddingTop: spacing.lg, paddingBottom: spacing.lg },
  dashboardContent: { flex: 1, paddingHorizontal: spacing.xl, paddingTop: spacing.sm, paddingBottom: spacing.lg },
  dashboardActivitySection: { position: "relative" },
  dashboardTransactionMeasurement: { position: "absolute", left: 0, right: 0, top: 0, opacity: 0 },
  goalsContent: { paddingHorizontal: spacing.xl, paddingTop: spacing.sm, paddingBottom: spacing.massive },
  goalsMockTopBar: { position: "absolute", top: spacing.sm, right: spacing.xl, zIndex: 1 },
  goalsMockAvatar: { width: 44, height: 44 },
  goalsMockContent: { flexGrow: 1, paddingHorizontal: spacing.xl, paddingTop: spacing.xl, paddingBottom: spacing.massive },
  goalsBack: { flexDirection: "row", alignItems: "center", gap: spacing.sm, height: 36, marginBottom: 22 },
  goalsBackText: { fontFamily: "Inter-Regular", fontSize: 12, color: colors.accent },
  goalsMockTitle: { ...typography.heading, color: colors.text, marginBottom: 22 },
  goalsCreateButton: { width: "100%", marginTop: "auto" },
  goalsEmptyMock: { marginTop: 55, alignItems: "flex-start" },
  goalsEmptyIcon: { width: 42, height: 42, borderRadius: 21, backgroundColor: colors.primarySoft, alignItems: "center", justifyContent: "center", marginBottom: 24 },
  goalsEmptyTitle: { ...typography.section, color: colors.text, marginBottom: 8 },
  goalsEmptyCopy: { ...typography.small, color: colors.textMuted },
  goalsEmptyButton: { width: "100%", marginTop: 24 },
  flex: { flex: 1, minWidth: 0 },
  dashboardHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: spacing.lg },
  dashboardGreeting: { fontFamily: "SourceSerifPro-Regular", color: colors.text, fontSize: 23, lineHeight: 28, letterSpacing: -0.5 },
  dashboardMonth: { ...typography.small, color: colors.textMuted, marginTop: 3 },
  avatar: { width: control.iconSize, height: control.iconSize, borderRadius: radius.circle, backgroundColor: colors.surfaceMuted, borderWidth: 1, borderColor: colors.border, alignItems: "center", justifyContent: "center" },
  avatarText: { fontFamily: "Inter-SemiBold", color: colors.text, fontSize: 14 },
  safeHeroCard: { backgroundColor: colors.primary, borderRadius: 16, paddingHorizontal: 22, paddingTop: 26, paddingBottom: 20, marginBottom: 18, overflow: "hidden", shadowColor: colors.text, shadowOffset: { width: 0, height: 9 }, shadowOpacity: 0.08, shadowRadius: 20, elevation: 2 },
  balanceDecoration: { position: "absolute", width: 190, height: 190, right: -90, top: -95, borderRadius: 95, borderWidth: 1, borderColor: "rgba(214,191,152,0.125)" },
  balanceDecorationOuterOne: { position: "absolute", width: 228, height: 228, right: -109, top: -114, borderRadius: 114, borderWidth: 1, borderColor: "rgba(214,191,152,0.024)" },
  balanceDecorationOuterTwo: { position: "absolute", width: 266, height: 266, right: -128, top: -133, borderRadius: 133, borderWidth: 1, borderColor: "rgba(214,191,152,0.016)" },
  balanceDecimals: { fontFamily: "Inter-Regular", fontSize: 26, color: "#D5CBBC" },
  balanceCaption: { fontFamily: "Inter-Regular", fontSize: 11, lineHeight: 17, color: "#D5CBBC" },
  dashboardGoalPreview: { alignSelf: "stretch", alignItems: "stretch", backgroundColor: colors.primary, borderWidth: 1, borderColor: colors.primary, borderRadius: radius.card, padding: spacing.lg, marginTop: spacing.sm, marginBottom: spacing.lg },
  dashboardGoalHeading: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.md },
  dashboardGoalName: { fontFamily: "Inter-SemiBold", fontSize: 13, lineHeight: 18, color: colors.background },
  dashboardGoalMeta: { ...typography.small, color: "#D5CBBC", marginTop: 2 },
  dashboardGoalProgress: { alignSelf: "stretch", height: 3, borderRadius: 1.5, marginTop: spacing.sm },
  dashboardGoalFooter: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: spacing.xs },
  dashboardGoalFooterText: { ...typography.small, fontSize: 11, lineHeight: 16, color: "#D5CBBC" },
  safeHeroHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  safeHeroLabelRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm },
  safeHeroIcon: { width: 28, height: 28, borderRadius: 14, backgroundColor: "rgba(255,255,255,0.18)", alignItems: "center", justifyContent: "center" },
  safeHeroLabel: { ...typography.small, fontSize: 11, color: "#D5CBBC" },
  safeHeroAmount: { fontFamily: "Inter-Regular", fontSize: 38, lineHeight: 46, letterSpacing: -1.3, color: colors.background, marginTop: 17, marginBottom: 27 },
  safeHeroStatus: { ...typography.small, color: "#C8D7C9", marginTop: spacing.xs },
  safeHeroStatusWarning: { color: "#FFE8A6" },
  safeHeroStatusDanger: { color: "#FFD2CE" },
  safeHeroStatusNeutral: { color: "rgba(255,255,255,0.72)" },
  safeHeroCopy: { ...typography.body, fontSize: 14, color: "rgba(255,255,255,0.78)", marginTop: spacing.xs },
  balanceMetaRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 0, marginBottom: 12, gap: spacing.sm },
  balanceProgress: { height: 4, borderRadius: 2, marginTop: 0, marginBottom: 10 },
  safeHeroProgress: { height: 8, borderRadius: 4, marginTop: spacing.xl },
  safeHeroFooter: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.sm, borderTopWidth: 1, borderTopColor: "rgba(255,255,255,0.13)", marginTop: spacing.lg, paddingTop: 13 },
  safeHeroLink: { ...typography.small, color: "#D7BC95", fontFamily: "Inter-SemiBold" },
  safeHeroPill: { backgroundColor: "rgba(255,255,255,0.72)", borderRadius: radius.chip, paddingHorizontal: spacing.sm, paddingVertical: spacing.xs },
  safeHeroPillText: { ...typography.small, color: "rgba(255,255,255,0.78)", fontFamily: "Inter-SemiBold" },
  dashboardQuickActions: { flexDirection: "row", gap: 12, marginBottom: 24 },
  dashboardQuickActionsWithGoal: { marginBottom: spacing.lg },
  budgetSection: { padding: 0, marginBottom: spacing.xl, backgroundColor: "transparent" },
  budgetHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: spacing.lg },
  budgetLabel: { ...typography.small, fontSize: 12, color: colors.textMuted },
  budgetAvailable: { flexShrink: 1, fontFamily: "SourceSerifPro-Regular", fontSize: 26, color: colors.text, textAlign: "right" },
  budgetAvailableDanger: { color: colors.danger },
  budgetStatRow: { flexDirection: "row", justifyContent: "space-between", marginTop: spacing.xl },
  budgetStat: { flex: 1 },
  budgetStatRight: { alignItems: "flex-end", flex: 1 },
  budgetStatLabel: { ...typography.small, color: colors.textMuted },
  budgetStatValue: { fontFamily: "Inter-SemiBold", fontSize: 18, color: colors.text, marginTop: 2 },
  budgetProgress: { height: 5, borderRadius: 3, marginTop: 15 },
  budgetFooter: { flexDirection: "row", justifyContent: "space-between", marginTop: 10 },
  budgetFootText: { ...typography.small, fontSize: 11, color: colors.textMuted },
  dashboardAddExpense: { height: 52, borderRadius: radius.input, backgroundColor: colors.primary, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: spacing.sm, marginBottom: spacing.xxxl },
  dashboardAddExpenseText: { fontFamily: "Inter-SemiBold", fontSize: 16, color: colors.white },
  safeCard: { marginBottom: spacing.xxxl },
  safeLabel: { ...typography.label, color: colors.textMuted },
  safeAmount: { fontFamily: "Inter-Bold", fontSize: 30, color: colors.text, marginTop: spacing.xs },
  safeCopy: { ...typography.small, color: colors.textMuted, marginTop: spacing.xs },
  sectionGap: { height: spacing.sm },
  goalCard: { marginBottom: 0 },
  emptyGoalState: { marginBottom: spacing.md },
  activitySurface: { backgroundColor: "transparent", marginBottom: spacing.md },
  activityList: { marginBottom: 0 },
  activityEmpty: { marginBottom: spacing.md },
  addTransactionButton: { marginTop: spacing.sm },
  transactionDivider: { height: 0 },

  listHeader: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", marginTop: spacing.lg, marginBottom: spacing.lg },
  listBackButton: { marginBottom: 0, borderColor: colors.referenceBorder },
  listHeaderCopy: { flex: 1, marginLeft: spacing.md },
  listTitle: { ...typography.heading, color: colors.text },
  goalsTitle: { ...typography.heading, color: colors.text },
  goalsHeaderActions: { flexDirection: "row", alignItems: "center", gap: spacing.sm },
  goalAddButton: { width: control.iconSize, height: control.iconSize, borderRadius: radius.circle, backgroundColor: colors.surfaceMuted, borderWidth: 1, borderColor: colors.border, alignItems: "center", justifyContent: "center" },
  topAction: { width: control.iconSize, height: control.iconSize, borderRadius: radius.icon, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center" },
  pageSubtitle: { ...typography.body, color: colors.textMuted, marginTop: spacing.xs, marginBottom: spacing.xl },
  pageSection: { marginTop: spacing.xxl },
  goalsSummarySurface: { backgroundColor: colors.primary, borderRadius: radius.card, padding: spacing.xl, marginBottom: spacing.xxl },
  goalsSummaryLabel: { ...typography.label, color: "rgba(255,255,255,0.74)" },
  goalsSummaryAmount: { fontFamily: "Inter-Regular", fontSize: 38, lineHeight: 44, color: colors.white, marginTop: spacing.xs },
  goalsSummaryMeta: { ...typography.body, color: "rgba(255,255,255,0.78)", marginTop: spacing.xs },
  goalCardsList: { gap: spacing.sm, marginBottom: spacing.lg },
  goalsEmpty: { marginTop: 0 },

  metricRow: { flexDirection: "row", gap: spacing.md, marginBottom: spacing.xxl },
  metricCard: { flex: 1, padding: spacing.lg, backgroundColor: colors.surfaceMuted, borderColor: colors.surfaceMuted },
  metricLabel: { ...typography.small, color: colors.textMuted },
  metricValue: { fontFamily: "Inter-Bold", fontSize: 22, color: colors.text, marginTop: spacing.sm },
  insightCallout: { backgroundColor: colors.successSoft, borderColor: colors.successSoft, marginBottom: spacing.xxl },
  insightCalloutTitle: { fontFamily: "Inter-SemiBold", fontSize: 16, color: colors.success },
  insightCalloutCopy: { ...typography.small, color: colors.textMuted, marginTop: spacing.xs, lineHeight: 20 },
  categoryRow: { flexDirection: "row", alignItems: "center", paddingVertical: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.divider, gap: spacing.md },
  categoryRowLast: { borderBottomWidth: 0 },
  categoryName: { flex: 1, fontFamily: "Inter-SemiBold", color: colors.text, fontSize: 14 },
  categoryAmount: { fontFamily: "Inter-SemiBold", color: colors.text, fontSize: 14 },
  categoryBarTrack: { height: control.progressHeight, borderRadius: control.progressHeight / 2, backgroundColor: colors.border, marginTop: spacing.xs, overflow: "hidden" },
  categoryBarFill: { height: "100%", borderRadius: control.progressHeight / 2 },

  profileHeader: { alignItems: "center", marginBottom: spacing.xxxl },
  profileAvatar: { width: 72, height: 72, borderRadius: 20, backgroundColor: colors.primarySoft, alignItems: "center", justifyContent: "center", marginBottom: spacing.md },
  profileAvatarText: { fontFamily: "Inter-Bold", fontSize: 29, color: colors.primary },
  profileName: { fontFamily: "Inter-SemiBold", color: colors.text, fontSize: 22 },
  profileEmail: { ...typography.small, color: colors.textMuted, marginTop: 3 },
  detailRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.divider, gap: spacing.lg },
  detailLabel: { ...typography.small, color: colors.textMuted, flex: 1 },
  detailValue: { ...typography.section, color: colors.text, textAlign: "right" },
  categoryIcon: { width: control.iconSize, height: control.iconSize, borderRadius: radius.icon, alignItems: "center", justifyContent: "center" },
  preferenceRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: spacing.md, gap: spacing.lg },
  preferenceTitle: { ...typography.section, color: colors.text },
  preferenceSubtitle: { ...typography.small, color: colors.textMuted, marginTop: 2 },
  toggle: { width: 46, height: 28, borderRadius: radius.circle, backgroundColor: colors.border, padding: 3, justifyContent: "center" },
  toggleActive: { backgroundColor: colors.primary },
  toggleKnob: { width: 22, height: 22, borderRadius: 11, backgroundColor: colors.textSubtle },
  toggleKnobActive: { backgroundColor: colors.white, alignSelf: "flex-end" },
  logoutButton: { marginTop: spacing.lg, borderColor: colors.dangerSoft },
  logoutText: { color: colors.danger, fontFamily: "Inter-SemiBold" },
  changePasswordButton: { marginTop: spacing.md },
  disabledPreference: { opacity: 0.6 },

  expenseAmountCard: { alignItems: "center", paddingVertical: spacing.xxl, marginBottom: spacing.xxl, backgroundColor: colors.surfaceMuted, borderColor: colors.surfaceMuted },
  expenseAmountLabel: { ...typography.label, color: colors.textMuted },
  amountEntry: { flexDirection: "row", alignItems: "center", marginTop: spacing.xs },
  amountCurrency: { fontFamily: "Inter-SemiBold", fontSize: 30, color: colors.textMuted, marginRight: spacing.xs },
  expenseAmountInput: { minWidth: 120, padding: 0, fontFamily: "Inter-Bold", fontSize: 42, lineHeight: 48, color: colors.text, textAlign: "center" },
  expenseAmount: { fontFamily: "Inter-Bold", fontSize: 42, lineHeight: 48, color: colors.text, marginTop: spacing.sm },
  categoryGrid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, marginBottom: spacing.xxl },
  categoryChip: { width: "30.8%", minHeight: 80, borderWidth: 1, borderColor: colors.border, borderRadius: radius.input, paddingVertical: spacing.md, backgroundColor: colors.surface, alignItems: "center", justifyContent: "center" },
  categoryChipActive: { backgroundColor: colors.primarySoft, borderColor: colors.primary },
  categoryChipIcon: { minHeight: 20, alignItems: "center", justifyContent: "center" },
  categoryChipText: { ...typography.small, color: colors.textMuted, marginTop: spacing.xs, textAlign: "center" },
  categoryChipTextActive: { color: colors.primary, fontFamily: "Inter-SemiBold" },
  balancePreview: { marginBottom: spacing.xxl, backgroundColor: colors.surfaceMuted, borderColor: colors.surfaceMuted },
  reflectionSpendCard: { marginBottom: 0, backgroundColor: "transparent", borderWidth: 0, paddingHorizontal: 0, paddingVertical: 0 },
  reflectionMerchant: { ...typography.small, color: colors.text },
  reflectionAmount: { fontFamily: "Inter-Regular", fontSize: 34, lineHeight: 40, letterSpacing: -1, color: colors.text, marginTop: spacing.sm, marginBottom: spacing.xs },
  reflectionMeta: { ...typography.small, color: colors.textMuted },
  impactCard: { marginBottom: spacing.xxl, backgroundColor: colors.successSoft, borderColor: colors.successSoft },
  impactTitle: { fontFamily: "Inter-SemiBold", fontSize: 16, color: colors.success },
  impactCopy: { ...typography.small, color: colors.textMuted, lineHeight: 20, marginTop: spacing.xs },
  reflectionReasonLabel: { marginTop: spacing.xxl },
  reasonList: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, marginBottom: spacing.xl },
  reasonChip: { borderWidth: 1, borderColor: colors.border, borderRadius: radius.chip, backgroundColor: colors.surface, paddingHorizontal: spacing.md, paddingVertical: spacing.sm },
  reasonChipActive: { backgroundColor: colors.primarySoft, borderColor: colors.primary },
  reasonText: { ...typography.small, color: colors.textMuted },
  reasonTextActive: { color: colors.primary, fontFamily: "Inter-SemiBold" },
  reflectionHint: { textAlign: "center", marginTop: spacing.xl },
});
