import { StyleSheet } from "react-native";

export const nubankColors = {
  purple: "#7600B8",
  purpleDeep: "#62009A",
  purpleSoft: "#F3EAF8",
  background: "#FFFFFF",
  surface: "#FFFFFF",
  ink: "#17131A",
  muted: "#756F79",
  subtle: "#A6A0A9",
  divider: "#ECE9EE",
  quiet: "#F6F4F7",
  green: "#2A9C68",
  amber: "#B97817",
  red: "#C94747",
};

export const nubankStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: nubankColors.background },
  content: { paddingHorizontal: 0, paddingBottom: 0, backgroundColor: nubankColors.background },
  purpleHeader: { backgroundColor: nubankColors.purple, paddingHorizontal: 20, paddingTop: 22, paddingBottom: 28 },
  headerTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 26 },
  headerIdentity: { flexDirection: "row", alignItems: "center", gap: 10, flex: 1, minWidth: 0 },
  avatar: { width: 36, height: 36, borderRadius: 18, backgroundColor: nubankColors.surface, alignItems: "center", justifyContent: "center" },
  avatarText: { fontFamily: "SourceSansPro-Bold", fontSize: 16, color: nubankColors.purple },
  headerBrand: { fontFamily: "SourceSansPro-SemiBold", fontSize: 16, color: nubankColors.surface },
  headerMeta: { fontFamily: "SourceSansPro-Regular", fontSize: 12, lineHeight: 16, color: "#EBDCF1", marginTop: 1 },
  headerIconRow: { flexDirection: "row", alignItems: "center", gap: 16 },
  headerIcon: { padding: 2 },
  safeLabel: { fontFamily: "SourceSansPro-SemiBold", fontSize: 12, lineHeight: 16, color: "#EBDCF1", textTransform: "uppercase", letterSpacing: 0.7 },
  safeAmount: { fontFamily: "SourceSansPro-Bold", fontSize: 40, lineHeight: 44, color: nubankColors.surface, letterSpacing: -0.8, marginTop: 8 },
  safeStatus: { fontFamily: "SourceSansPro-SemiBold", fontSize: 14, lineHeight: 19, color: nubankColors.surface, marginTop: 6 },
  safeStatusDanger: { color: "#FFE1E1" },
  safeStatusWarning: { color: "#FFE9BA" },
  safeStatusNeutral: { color: "#EBDCF1" },
  safeCopy: { fontFamily: "SourceSansPro-Regular", fontSize: 13, lineHeight: 18, color: "#EBDCF1", marginTop: 8 },
  main: { paddingHorizontal: 20 },
  quickSection: { paddingTop: 22, paddingBottom: 20, borderBottomWidth: 1, borderBottomColor: nubankColors.divider },
  sectionEyebrow: { fontFamily: "SourceSansPro-SemiBold", fontSize: 12, lineHeight: 16, color: nubankColors.muted, textTransform: "uppercase", letterSpacing: 0.65 },
  actionRow: { flexDirection: "row", justifyContent: "space-between", marginTop: 14 },
  action: { alignItems: "center", width: "31%", gap: 7 },
  actionCircle: { width: 48, height: 48, borderRadius: 24, backgroundColor: nubankColors.quiet, alignItems: "center", justifyContent: "center" },
  actionCirclePrimary: { backgroundColor: nubankColors.purple },
  actionLabel: { fontFamily: "SourceSansPro-SemiBold", fontSize: 12, lineHeight: 15, color: nubankColors.ink, textAlign: "center" },
  section: { paddingVertical: 21, borderBottomWidth: 1, borderBottomColor: nubankColors.divider },
  sectionHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 16 },
  sectionTitle: { fontFamily: "SourceSansPro-Bold", fontSize: 20, lineHeight: 24, color: nubankColors.ink, letterSpacing: -0.2 },
  sectionLink: { fontFamily: "SourceSansPro-SemiBold", fontSize: 12, color: nubankColors.purple },
  moneyRow: { flexDirection: "row", justifyContent: "space-between", gap: 16 },
  stat: { flex: 1, minWidth: 0 },
  statRight: { alignItems: "flex-end" },
  statLabel: { fontFamily: "SourceSansPro-Regular", fontSize: 12, lineHeight: 16, color: nubankColors.muted },
  statValue: { fontFamily: "SourceSansPro-Bold", fontSize: 22, lineHeight: 27, color: nubankColors.ink, marginTop: 3 },
  statMeta: { fontFamily: "SourceSansPro-Regular", fontSize: 12, lineHeight: 16, color: nubankColors.muted, marginTop: 3 },
  progressTrack: { height: 5, borderRadius: 3, backgroundColor: "#EEEAF2", overflow: "hidden", marginTop: 17 },
  progressFill: { height: "100%", borderRadius: 3, backgroundColor: nubankColors.purple },
  budgetFooter: { flexDirection: "row", justifyContent: "space-between", marginTop: 8 },
  footerText: { fontFamily: "SourceSansPro-SemiBold", fontSize: 12, lineHeight: 16, color: nubankColors.muted },
  footerTextAccent: { color: nubankColors.purple },
  goalRow: { paddingBottom: 2 },
  goalTop: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 12 },
  goalCopy: { flex: 1, minWidth: 0 },
  goalName: { fontFamily: "SourceSansPro-SemiBold", fontSize: 16, lineHeight: 20, color: nubankColors.ink },
  goalAmount: { fontFamily: "SourceSansPro-Bold", fontSize: 18, lineHeight: 23, color: nubankColors.ink, marginTop: 4 },
  goalTarget: { fontFamily: "SourceSansPro-Regular", fontSize: 12, lineHeight: 16, color: nubankColors.muted, marginTop: 1 },
  goalPercent: { fontFamily: "SourceSansPro-Bold", fontSize: 17, lineHeight: 21, color: nubankColors.purple },
  goalPercentLabel: { fontFamily: "SourceSansPro-Regular", fontSize: 11, lineHeight: 15, color: nubankColors.muted, textAlign: "right", marginTop: 1 },
  goalFooter: { flexDirection: "row", justifyContent: "space-between", marginTop: 8 },
  goalFooterText: { fontFamily: "SourceSansPro-SemiBold", fontSize: 12, lineHeight: 16, color: nubankColors.muted },
  recentList: { marginTop: -3 },
  transactionRow: { flexDirection: "row", alignItems: "center", gap: 12, minHeight: 60, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: nubankColors.divider },
  transactionRowLast: { borderBottomWidth: 0 },
  transactionIcon: { width: 34, height: 34, borderRadius: 17, alignItems: "center", justifyContent: "center" },
  transactionCopy: { flex: 1, minWidth: 0 },
  transactionTitle: { fontFamily: "SourceSansPro-SemiBold", fontSize: 14, lineHeight: 18, color: nubankColors.ink },
  transactionMeta: { fontFamily: "SourceSansPro-Regular", fontSize: 11, lineHeight: 15, color: nubankColors.muted, marginTop: 1 },
  transactionAmount: { fontFamily: "SourceSansPro-SemiBold", fontSize: 14, lineHeight: 18, color: nubankColors.ink, textAlign: "right" },
  emptyCopy: { fontFamily: "SourceSansPro-Regular", fontSize: 14, lineHeight: 20, color: nubankColors.muted },
  bottomNav: { flexDirection: "row", paddingHorizontal: 12, paddingTop: 10, paddingBottom: 15, borderTopWidth: 1, borderTopColor: nubankColors.divider, backgroundColor: nubankColors.surface },
  bottomNavItem: { flex: 1, alignItems: "center", gap: 4 },
  bottomNavLabel: { fontFamily: "SourceSansPro-SemiBold", fontSize: 11, lineHeight: 14, color: nubankColors.subtle },
  bottomNavLabelActive: { color: nubankColors.purple },
  goalsHeader: { paddingHorizontal: 20, paddingTop: 22, paddingBottom: 16, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  goalsHeaderLeft: { flexDirection: "row", alignItems: "center", gap: 12, flex: 1, minWidth: 0 },
  headerBack: { width: 28, height: 32, alignItems: "flex-start", justifyContent: "center" },
  goalsTitle: { fontFamily: "SourceSansPro-Bold", fontSize: 28, lineHeight: 33, color: nubankColors.ink, letterSpacing: -0.3 },
  goalsHeaderMeta: { fontFamily: "SourceSansPro-Regular", fontSize: 12, lineHeight: 16, color: nubankColors.muted, marginTop: 1 },
  addButton: { width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center", backgroundColor: nubankColors.purple },
  totalSection: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 23, borderBottomWidth: 1, borderBottomColor: nubankColors.divider },
  totalLabel: { fontFamily: "SourceSansPro-SemiBold", fontSize: 12, lineHeight: 16, color: nubankColors.muted, textTransform: "uppercase", letterSpacing: 0.7 },
  totalAmount: { fontFamily: "SourceSansPro-Bold", fontSize: 36, lineHeight: 42, color: nubankColors.ink, letterSpacing: -0.6, marginTop: 5 },
  totalMeta: { fontFamily: "SourceSansPro-Regular", fontSize: 13, lineHeight: 18, color: nubankColors.muted, marginTop: 3 },
  totalProgress: { marginTop: 17 },
  tabRow: { flexDirection: "row", paddingHorizontal: 20, borderBottomWidth: 1, borderBottomColor: nubankColors.divider },
  tabButton: { paddingVertical: 14, marginRight: 25, borderBottomWidth: 2, borderBottomColor: "transparent" },
  tabButtonActive: { borderBottomColor: nubankColors.purple },
  tabText: { fontFamily: "SourceSansPro-SemiBold", fontSize: 14, lineHeight: 18, color: nubankColors.muted },
  tabTextActive: { color: nubankColors.purple },
  goalSection: { paddingHorizontal: 20 },
  listHeadingRow: { flexDirection: "row", alignItems: "baseline", justifyContent: "space-between", paddingTop: 23, paddingBottom: 4 },
  listHeading: { fontFamily: "SourceSansPro-Bold", fontSize: 20, lineHeight: 25, color: nubankColors.ink },
  listCount: { fontFamily: "SourceSansPro-Regular", fontSize: 12, lineHeight: 16, color: nubankColors.muted },
  openGoalRow: { paddingVertical: 17, borderBottomWidth: 1, borderBottomColor: nubankColors.divider },
  completedGoalRow: { backgroundColor: nubankColors.background },
  goalRowHeader: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 12 },
  goalRowName: { flex: 1, minWidth: 0, fontFamily: "SourceSansPro-SemiBold", fontSize: 16, lineHeight: 21, color: nubankColors.ink },
  goalRowAmount: { fontFamily: "SourceSansPro-Bold", fontSize: 19, lineHeight: 24, color: nubankColors.ink, marginTop: 5 },
  goalRowTarget: { fontFamily: "SourceSansPro-Regular", fontSize: 12, lineHeight: 16, color: nubankColors.muted, marginTop: 1 },
  goalRowPercent: { fontFamily: "SourceSansPro-Bold", fontSize: 16, lineHeight: 20, color: nubankColors.purple },
  goalRowPercentCompleted: { color: nubankColors.green },
  goalRowProgress: { marginTop: 14 },
  goalRowFooter: { flexDirection: "row", justifyContent: "space-between", marginTop: 8 },
  goalRowFooterText: { fontFamily: "SourceSansPro-SemiBold", fontSize: 12, lineHeight: 16, color: nubankColors.muted },
  emptyGoals: { paddingVertical: 52, alignItems: "flex-start" },
  emptyGoalsTitle: { fontFamily: "SourceSansPro-Bold", fontSize: 21, lineHeight: 26, color: nubankColors.ink },
  emptyGoalsDescription: { fontFamily: "SourceSansPro-Regular", fontSize: 14, lineHeight: 20, color: nubankColors.muted, marginTop: 6, maxWidth: 280 },
  emptyGoalsButton: { marginTop: 18, minHeight: 42, paddingHorizontal: 18, borderRadius: 21, alignItems: "center", justifyContent: "center", backgroundColor: nubankColors.purple },
  emptyGoalsButtonText: { fontFamily: "SourceSansPro-SemiBold", fontSize: 13, color: nubankColors.surface },
});
