import { StyleSheet } from "react-native";

export const cashColors = {
  background: "#0A0A0B",
  surface: "#151516",
  surfaceRaised: "#1C1C1E",
  text: "#FFFFFF",
  textMuted: "#A4A4A8",
  textSubtle: "#6F6F75",
  purple: "#7657F6",
  purpleSoft: "#2B245A",
  green: "#5ECF87",
  divider: "#27272A",
  red: "#FF6969",
};

export const cashStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: cashColors.background },
  content: { paddingHorizontal: 18, paddingBottom: 0, backgroundColor: cashColors.background },
  header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingTop: 20, paddingBottom: 24 },
  headerCopy: { flex: 1, minWidth: 0 },
  brand: { fontFamily: "SourceSansPro-Bold", fontSize: 23, lineHeight: 28, color: cashColors.text, letterSpacing: -0.2 },
  headerMeta: { fontFamily: "SourceSansPro-Regular", fontSize: 12, lineHeight: 16, color: cashColors.textMuted, marginTop: 2 },
  avatar: { width: 38, height: 38, borderRadius: 19, backgroundColor: cashColors.purple, alignItems: "center", justifyContent: "center" },
  avatarText: { fontFamily: "SourceSansPro-Bold", fontSize: 16, color: cashColors.text },
  safeSection: { paddingBottom: 24, borderBottomWidth: 1, borderBottomColor: cashColors.divider },
  eyebrow: { fontFamily: "SourceSansPro-SemiBold", fontSize: 12, lineHeight: 16, color: cashColors.textMuted, textTransform: "uppercase", letterSpacing: 0.75 },
  safeAmount: { fontFamily: "SourceSansPro-Bold", fontSize: 47, lineHeight: 52, color: cashColors.text, letterSpacing: -1.1, marginTop: 7 },
  safeToday: { fontFamily: "SourceSansPro-SemiBold", fontSize: 15, lineHeight: 19, color: cashColors.purple, marginTop: 3 },
  safeMeta: { fontFamily: "SourceSansPro-Regular", fontSize: 13, lineHeight: 18, color: cashColors.textMuted, marginTop: 13 },
  status: { fontFamily: "SourceSansPro-SemiBold", fontSize: 13, lineHeight: 17, color: cashColors.green, marginTop: 5 },
  statusWarning: { color: "#F4BD4F" },
  statusDanger: { color: cashColors.red },
  statusNeutral: { color: cashColors.textMuted },
  primaryAction: { minHeight: 52, borderRadius: 26, alignItems: "center", justifyContent: "center", backgroundColor: cashColors.purple, marginTop: 20 },
  primaryActionText: { fontFamily: "SourceSansPro-Bold", fontSize: 16, lineHeight: 20, color: cashColors.text },
  actionRow: { flexDirection: "row", gap: 10, marginTop: 13 },
  action: { flex: 1, minHeight: 74, alignItems: "center", justifyContent: "center", gap: 5, borderWidth: 1, borderColor: cashColors.divider, borderRadius: 12, backgroundColor: cashColors.surface },
  actionCircle: { width: 30, height: 30, borderRadius: 15, alignItems: "center", justifyContent: "center", backgroundColor: cashColors.surfaceRaised },
  actionCircleGreen: { backgroundColor: "#1D5035" },
  actionLabel: { fontFamily: "SourceSansPro-SemiBold", fontSize: 12, lineHeight: 15, color: cashColors.text },
  section: { paddingTop: 23, paddingBottom: 21, borderBottomWidth: 1, borderBottomColor: cashColors.divider },
  sectionHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 14 },
  sectionTitle: { fontFamily: "SourceSansPro-SemiBold", fontSize: 18, lineHeight: 23, color: cashColors.text },
  sectionLink: { fontFamily: "SourceSansPro-SemiBold", fontSize: 12, color: cashColors.purple },
  goalSurface: { backgroundColor: cashColors.surface, borderWidth: 1, borderColor: cashColors.divider, borderRadius: 14, padding: 16 },
  goalTop: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 12 },
  goalCopy: { flex: 1, minWidth: 0 },
  goalName: { fontFamily: "SourceSansPro-SemiBold", fontSize: 16, lineHeight: 21, color: cashColors.text },
  goalAmount: { fontFamily: "SourceSansPro-Bold", fontSize: 27, lineHeight: 32, color: cashColors.text, marginTop: 7 },
  goalTarget: { fontFamily: "SourceSansPro-Regular", fontSize: 12, lineHeight: 16, color: cashColors.textMuted, marginTop: 1 },
  goalPercent: { fontFamily: "SourceSansPro-Bold", fontSize: 20, lineHeight: 25, color: cashColors.purple },
  goalProgress: { height: 6, borderRadius: 3, backgroundColor: cashColors.divider, overflow: "hidden", marginTop: 17 },
  goalProgressFill: { height: "100%", borderRadius: 3, backgroundColor: cashColors.purple },
  goalFooter: { flexDirection: "row", justifyContent: "space-between", marginTop: 9 },
  goalFooterText: { fontFamily: "SourceSansPro-Regular", fontSize: 12, lineHeight: 16, color: cashColors.textMuted },
  moreGoals: { fontFamily: "SourceSansPro-Regular", fontSize: 12, lineHeight: 16, color: cashColors.textSubtle, marginTop: 12 },
  recentRow: { flexDirection: "row", alignItems: "center", minHeight: 52, paddingVertical: 9, borderBottomWidth: 1, borderBottomColor: cashColors.divider },
  recentRowLast: { borderBottomWidth: 0 },
  recentCopy: { flex: 1, minWidth: 0 },
  recentTitle: { fontFamily: "SourceSansPro-SemiBold", fontSize: 15, lineHeight: 19, color: cashColors.text },
  recentMeta: { fontFamily: "SourceSansPro-Regular", fontSize: 11, lineHeight: 15, color: cashColors.textMuted, marginTop: 1 },
  recentAmount: { fontFamily: "SourceSansPro-SemiBold", fontSize: 14, lineHeight: 18, color: cashColors.text, textAlign: "right" },
  emptyCopy: { fontFamily: "SourceSansPro-Regular", fontSize: 14, lineHeight: 20, color: cashColors.textMuted },
  bottomNav: { flexDirection: "row", paddingTop: 13, paddingBottom: 16, backgroundColor: cashColors.background, borderTopWidth: 1, borderTopColor: cashColors.divider },
  bottomNavItem: { flex: 1, alignItems: "center", gap: 4 },
  bottomNavLabel: { fontFamily: "SourceSansPro-SemiBold", fontSize: 10, lineHeight: 13, color: cashColors.textSubtle },
  bottomNavLabelActive: { color: cashColors.purple },
  goalsHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingTop: 20, paddingBottom: 23 },
  goalsTitle: { fontFamily: "SourceSansPro-Bold", fontSize: 30, lineHeight: 35, color: cashColors.text, letterSpacing: -0.4 },
  goalsHeaderMeta: { fontFamily: "SourceSansPro-Regular", fontSize: 12, lineHeight: 16, color: cashColors.textMuted, marginTop: 3 },
  addButton: { width: 42, height: 42, borderRadius: 21, alignItems: "center", justifyContent: "center", backgroundColor: cashColors.purple },
  totalSection: { paddingBottom: 23, borderBottomWidth: 1, borderBottomColor: cashColors.divider },
  totalLabel: { fontFamily: "SourceSansPro-SemiBold", fontSize: 12, lineHeight: 16, color: cashColors.textMuted, textTransform: "uppercase", letterSpacing: 0.75 },
  totalAmount: { fontFamily: "SourceSansPro-Bold", fontSize: 43, lineHeight: 48, color: cashColors.text, letterSpacing: -0.9, marginTop: 6 },
  totalMeta: { fontFamily: "SourceSansPro-Regular", fontSize: 13, lineHeight: 17, color: cashColors.textMuted, marginTop: 4 },
  activeHeading: { fontFamily: "SourceSansPro-SemiBold", fontSize: 18, lineHeight: 23, color: cashColors.text, marginTop: 24, marginBottom: 7 },
  openGoalRow: { paddingVertical: 17, borderBottomWidth: 1, borderBottomColor: cashColors.divider },
  goalRowHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: 12 },
  goalRowName: { flex: 1, minWidth: 0, fontFamily: "SourceSansPro-SemiBold", fontSize: 16, lineHeight: 21, color: cashColors.text },
  goalRowAmount: { fontFamily: "SourceSansPro-Bold", fontSize: 20, lineHeight: 25, color: cashColors.text, marginTop: 5 },
  goalRowTarget: { fontFamily: "SourceSansPro-Regular", fontSize: 12, lineHeight: 16, color: cashColors.textMuted, marginTop: 1 },
  goalRowPercent: { fontFamily: "SourceSansPro-SemiBold", fontSize: 14, lineHeight: 18, color: cashColors.purple },
  goalRowProgress: { height: 4, borderRadius: 2, backgroundColor: cashColors.divider, overflow: "hidden", marginTop: 13 },
  goalRowProgressFill: { height: "100%", borderRadius: 2, backgroundColor: cashColors.purple },
  goalRowFooter: { flexDirection: "row", justifyContent: "space-between", marginTop: 7 },
  goalRowFooterText: { fontFamily: "SourceSansPro-Regular", fontSize: 11, lineHeight: 15, color: cashColors.textMuted },
  completedHeading: { fontFamily: "SourceSansPro-SemiBold", fontSize: 18, lineHeight: 23, color: cashColors.text, marginTop: 25, marginBottom: 7 },
  completedDot: { width: 9, height: 9, borderRadius: 5, backgroundColor: cashColors.green, marginRight: 8, marginTop: 5 },
  completedNameRow: { flexDirection: "row", alignItems: "flex-start", flex: 1, minWidth: 0 },
  completedStatus: { fontFamily: "SourceSansPro-SemiBold", fontSize: 12, lineHeight: 16, color: cashColors.green },
  emptyGoals: { paddingVertical: 50 },
  emptyGoalsTitle: { fontFamily: "SourceSansPro-Bold", fontSize: 22, lineHeight: 27, color: cashColors.text },
  emptyGoalsDescription: { fontFamily: "SourceSansPro-Regular", fontSize: 14, lineHeight: 20, color: cashColors.textMuted, marginTop: 6 },
  emptyGoalsButton: { alignSelf: "flex-start", minHeight: 44, paddingHorizontal: 18, borderRadius: 22, alignItems: "center", justifyContent: "center", backgroundColor: cashColors.purple, marginTop: 18 },
  emptyGoalsButtonText: { fontFamily: "SourceSansPro-SemiBold", fontSize: 13, color: cashColors.text },
});
