import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: "#111210",
  },
  scrollContainer: {
    paddingHorizontal: 20,
    flexGrow: 1,
  },
  previewCard: {
    backgroundColor: "rgba(26, 28, 25, 0.75)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    borderRadius: 20,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    overflow: "hidden",
  },
  previewImageContainer: {
    width: 64,
    height: 64,
    borderRadius: 10,
    backgroundColor: "#111210",
    borderWidth: 1,
    borderColor: "#2C2D35",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  previewImage: {
    width: "100%",
    height: "100%",
  },
  previewInfoContainer: {
    flex: 1,
    marginLeft: 14,
  },
  previewLabel: {
    fontSize: 9,
    color: "#8A90A8",
    fontFamily: "DMSerifDisplay-Regular",
    letterSpacing: 0.5,
  },
  previewTitle: {
    fontSize: 14,
    color: "#FFFFFF",
    fontFamily: "DMSerifDisplay-Regular",
  },
  previewPrice: {
    fontSize: 16,
    color: "#9D4EDD",
    fontFamily: "DMSerifDisplay-Regular",
  },
  searchCard: {
    backgroundColor: "rgba(26, 28, 25, 0.75)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    borderRadius: 20,
    padding: 16,
    marginBottom: 16,
    overflow: "hidden",
  },
  sectionTitle: {
    fontSize: 16,
    color: "#FFFFFF",
    fontFamily: "DMSerifDisplay-Regular",
    marginBottom: 14,
  },
  searchBarContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(17, 18, 16, 0.68)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    borderRadius: 12,
    height: 48,
    paddingHorizontal: 12,
    marginBottom: 14,
  },
  searchBarContainerFocused: {
    borderColor: "#9D4EDD",
  },
  searchIcon: {
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: "#FFFFFF",
    fontFamily: "DMSerifDisplay-Regular",
  },
  resultsWrapper: {
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.04)",
  },
  resultItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.04)",
  },
  resultImage: {
    width: 38,
    height: 38,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#2C2D35",
  },
  resultInfo: {
    flex: 1,
    marginLeft: 12,
    justifyContent: "center",
  },
  resultTitle: {
    fontSize: 13,
    color: "#FFFFFF",
    fontFamily: "DMSerifDisplay-Regular",
  },
  resultSource: {
    fontSize: 10,
    color: "#8A90A8",
    fontFamily: "DMSerifDisplay-Regular",
    marginTop: 1,
  },
  resultPrice: {
    fontSize: 13,
    color: "#9D4EDD",
    fontFamily: "DMSerifDisplay-Regular",
    marginLeft: 8,
  },
  updateButtonContainer: {
    width: "100%",
    height: 50,
    borderRadius: 25,
    shadowColor: "#7B2CBF",
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
    marginTop: 10,
  },
  buttonScaleWrapper: {
    flex: 1,
  },
  updateButtonGradient: {
    flex: 1,
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
  },
  updateButtonText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontFamily: "DMSerifDisplay-Regular",
    letterSpacing: 0.5,
  },
  confirmPanel: {
    width: "100%",
  },
  confirmButton: {
    flex: 1,
    height: 40,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: 6,
  },
  confirmButtonCancel: {
    backgroundColor: "rgba(17, 18, 16, 0.68)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  confirmButtonConfirm: {
    backgroundColor: "#9D4EDD",
  },
  confirmButtonCancelText: {
    color: "#8A90A8",
    fontSize: 13,
    fontFamily: "DMSerifDisplay-Regular",
  },
  confirmButtonConfirmText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontFamily: "DMSerifDisplay-Regular",
  },
  inputLabel: {
    fontSize: 12,
    color: "#8A90A8",
    fontFamily: "DMSerifDisplay-Regular",
    marginBottom: 6,
  },
  currencyPrefix: {
    fontSize: 16,
    marginRight: 6,
    fontFamily: "DMSerifDisplay-Regular",
    color: "#8A90A8",
  },
  estimatorCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(106, 201, 122, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(106, 201, 122, 0.15)",
    borderRadius: 10,
    padding: 12,
    marginTop: 16,
  },
  estimatorText: {
    flex: 1,
    fontSize: 13,
    color: "#ECEEF4",
    fontFamily: "DMSerifDisplay-Regular",
    lineHeight: 18,
  },
  estimatorHighlight: {
    color: "#9D4EDD",
  },
});

